"""empty message

Revision ID: 610af2f7199e
Revises: c5347ad1f4ce
Create Date: 2017-12-08 18:21:20.842534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '610af2f7199e'
down_revision = 'c5347ad1f4ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('posted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'posted')
    # ### end Alembic commands ###
